apiVersion: v1
kind: Config
current-context: garden-ai-trust--ai-trust-1-external
contexts:
  - name: garden-ai-trust--ai-trust-1-external
    context:
      cluster: garden-ai-trust--ai-trust-1-external
      user: garden-ai-trust--ai-trust-1
      namespace: default
  - name: garden-ai-trust--ai-trust-1-internal
    context:
      cluster: garden-ai-trust--ai-trust-1-internal
      user: garden-ai-trust--ai-trust-1
      namespace: default
clusters:
  - name: garden-ai-trust--ai-trust-1-external
    cluster:
      server: >-
        https://api.ai-trust-1.ai-trust.shoot.gardener.cc-one.showroom.apeirora.eu
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRVnVlK0dzNzdUSU04bXQzOVlGYk45akFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBNE1UQXdOek01TWpSYUZ3MHpOakE0TVRBd056UXdNalJhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUF2LzI0CjhxenhKR00xTGJzbjNMTjlLMlAyT2RxNmZXdWsweDBVRml1SFJpT0dRM1J1Y0x3Sm54bitSbWQ1YkpUY3NLR0EKRnVJTUloYURQU1hxY2xDT0Jza0JCN2pJNWkxYUh3TjhXN2ZOaEc3TENlN3ZwTSs3WDB5NDMzVElrRzZrWXBSSwprckZjM1hIbE5TeCtRdHlZSWRyYytrUTRNbi9xT3RYRmY5VnZHdEtpaXhyZXlvRkEvcXAzOUp5cXNaMWFHUlVrCmZNaUUwVEFGOCtaclJuVm5KN1VuWUNBdlhjNTBWTnBXekFLcFBpaUZ6aWRCcjRRZEd6eTd1N3FhM0hTc3BCQnAKTDRIS1hxcndTRHJkengrcElaV3o3bUFSWGR5UC9DNEx6V0k1Q0duMEFURXpncFg2cXdJSGVad1RjZWhmbUZSZApRYXZQaTk3aytUT1ZSdzlHWkpTK0d5SUxLeHo4Q0N4YlRRalJXeTA4V1ZmM25scTh6aWZKeGUzVG94cEdGRHJGCmljczRCMW1rdi84b2Z0amQ3TEZsUUYvWXRobHYwekRnRHdOa2Rsem5HZ1FlWk5SNmY0eXN5SXkyNytLK2VwSXAKdTBnNyt1OWhCYng3LzBPQm9qRXU3VFZFZGJRdmJkb08zc1BSazVKaGl3YjRPQXFQQkg0UXJHUjZUZXdmQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUk03bEVhRjRNLzFuN2F4V1kwTTMwUUFTaDl2VEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBWDF1REE5Y08KOWZsdldUQzI1ZEVielg2L3BVTnJaRlVTZE1QWlF6all5SzJHd1ZnbnhGSjJqVm9KZnFHamtVN016M1d1V2hqVwpyVGNtTzR3YUNkbWxpM2s5NVljN0dJb3pPT3g0K2RoVERPN0EwNkpZSWFGNms3YU5IRWFIYzlOdWJOTFFMdkY4CmNBTG4rbW45MmNGSG9yMTRiTGRqUXE4SGwzUUtjYUtQM2cxY1FZNFBGdm9zVHlzbU1sWVdST0tvRUN0UzllcFAKdjAxZmROc1dYd3V2bmMrblNRV0U0b29ZcHJRRFVqd3FDcVVsRWdkVkFuOUsyeUZrbkFnL3o4aE42Mzgra091agoxQUgzU0k1ZURLV0dBK2sxMCtReG1IUG1Xa2NLMUNtREk3TUJZRHZjaHd6aE13cjlrMFlSS0VSdStCaFlvVkRQCjhybENNb1VsanBac1R0Z0RCREpNaUVZVnFZa3NVM2tDU1lPeTNJQkFPR2ZnUlNDQXI4U3Y1aGhUQm1IRzRTNjAKbjFrUXlGdHlOZ3plRWFJOFcvSzF6QlZVRnZRM2FSU0Y5NnhsUE0zTm9wMmtWcGd0R2NFaDB2eitHbWNCM0h4QwpxdlFkUFBLMDA3R0dsekJYTjZqTjBEQ3Q0a0tFa1NCTHRUR3ZBUi9FYWdUS0hOVTczMFd5RjlVSQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      extensions: &ref_0
        - name: client.authentication.k8s.io/exec
          extension:
            shootRef:
              namespace: garden-ai-trust
              name: ai-trust-1
            gardenClusterIdentity: landscape-apeirora-one
  - name: garden-ai-trust--ai-trust-1-internal
    cluster:
      server: >-
        https://api.ai-trust-1.ai-trust.internal.gardener.cc-one.showroom.apeirora.eu
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRVnVlK0dzNzdUSU04bXQzOVlGYk45akFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBNE1UQXdOek01TWpSYUZ3MHpOakE0TVRBd056UXdNalJhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUF2LzI0CjhxenhKR00xTGJzbjNMTjlLMlAyT2RxNmZXdWsweDBVRml1SFJpT0dRM1J1Y0x3Sm54bitSbWQ1YkpUY3NLR0EKRnVJTUloYURQU1hxY2xDT0Jza0JCN2pJNWkxYUh3TjhXN2ZOaEc3TENlN3ZwTSs3WDB5NDMzVElrRzZrWXBSSwprckZjM1hIbE5TeCtRdHlZSWRyYytrUTRNbi9xT3RYRmY5VnZHdEtpaXhyZXlvRkEvcXAzOUp5cXNaMWFHUlVrCmZNaUUwVEFGOCtaclJuVm5KN1VuWUNBdlhjNTBWTnBXekFLcFBpaUZ6aWRCcjRRZEd6eTd1N3FhM0hTc3BCQnAKTDRIS1hxcndTRHJkengrcElaV3o3bUFSWGR5UC9DNEx6V0k1Q0duMEFURXpncFg2cXdJSGVad1RjZWhmbUZSZApRYXZQaTk3aytUT1ZSdzlHWkpTK0d5SUxLeHo4Q0N4YlRRalJXeTA4V1ZmM25scTh6aWZKeGUzVG94cEdGRHJGCmljczRCMW1rdi84b2Z0amQ3TEZsUUYvWXRobHYwekRnRHdOa2Rsem5HZ1FlWk5SNmY0eXN5SXkyNytLK2VwSXAKdTBnNyt1OWhCYng3LzBPQm9qRXU3VFZFZGJRdmJkb08zc1BSazVKaGl3YjRPQXFQQkg0UXJHUjZUZXdmQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUk03bEVhRjRNLzFuN2F4V1kwTTMwUUFTaDl2VEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBWDF1REE5Y08KOWZsdldUQzI1ZEVielg2L3BVTnJaRlVTZE1QWlF6all5SzJHd1ZnbnhGSjJqVm9KZnFHamtVN016M1d1V2hqVwpyVGNtTzR3YUNkbWxpM2s5NVljN0dJb3pPT3g0K2RoVERPN0EwNkpZSWFGNms3YU5IRWFIYzlOdWJOTFFMdkY4CmNBTG4rbW45MmNGSG9yMTRiTGRqUXE4SGwzUUtjYUtQM2cxY1FZNFBGdm9zVHlzbU1sWVdST0tvRUN0UzllcFAKdjAxZmROc1dYd3V2bmMrblNRV0U0b29ZcHJRRFVqd3FDcVVsRWdkVkFuOUsyeUZrbkFnL3o4aE42Mzgra091agoxQUgzU0k1ZURLV0dBK2sxMCtReG1IUG1Xa2NLMUNtREk3TUJZRHZjaHd6aE13cjlrMFlSS0VSdStCaFlvVkRQCjhybENNb1VsanBac1R0Z0RCREpNaUVZVnFZa3NVM2tDU1lPeTNJQkFPR2ZnUlNDQXI4U3Y1aGhUQm1IRzRTNjAKbjFrUXlGdHlOZ3plRWFJOFcvSzF6QlZVRnZRM2FSU0Y5NnhsUE0zTm9wMmtWcGd0R2NFaDB2eitHbWNCM0h4QwpxdlFkUFBLMDA3R0dsekJYTjZqTjBEQ3Q0a0tFa1NCTHRUR3ZBUi9FYWdUS0hOVTczMFd5RjlVSQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      extensions: *ref_0
users:
  - name: garden-ai-trust--ai-trust-1
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: kubectl-gardenlogin
        args:
          - get-client-certificate
        provideClusterInfo: true
        interactiveMode: IfAvailable
        installHint: >-
          Follow the instructions on

          - https://github.com/gardener/gardenlogin#installation to install and

          - https://github.com/gardener/gardenlogin#configure-gardenlogin to
          configure the gardenlogin credential plugin.


          The following is a sample configuration for gardenlogin as well as
          gardenctl. Place the file under ~/.garden/gardenctl-v2.yaml.


          ---

          gardens:
            - identity: landscape-apeirora-one
              kubeconfig: "<path-to-garden-cluster-kubeconfig>"
          ...


          Alternatively, you can run the following gardenctl command:


          $ gardenctl config set-garden landscape-apeirora-one --kubeconfig
          "<path-to-garden-cluster-kubeconfig>"


          Note that the kubeconfig refers to the path of the garden cluster
          kubeconfig which you can download from the Account page.
