export interface TraceFilters {
  trace_id?: string;
  service_name?: string;
  model?: string;
  from?: string;
  to?: string;
  errors_only?: boolean;
}

export interface Trace {
  trace_id: string;
  started_at: string;
  span_count: number;
  service_name: string;
  /**
   * Name of the trace's root span (the OTel span without a parent). Set by the
   * instrumented app — typically a use-case label like "agent.session",
   * "rag.pipeline", or "llm.chat". Empty string if the trace has no root span
   * (should not happen for well-formed OTel traces).
   */
  root_span_name: string;
  total_duration_s: number;
  total_tokens: number;
  request_model: string;
  /** True if any span in the trace has OTel status_code == 2 (ERROR). */
  has_error: boolean;
}

export interface Span {
  span_id: string;
  /** Empty string for root spans (no parent). */
  parent_span_id: string;
  started_at: string;
  duration_ms: number;
  operation_name: string;
  /** Top-level OTel span name (e.g. "ChatOllama", "AgentExecutor"). */
  span_name: string;
  /** OTel SpanKind enum: 0=UNSPECIFIED, 1=INTERNAL, 2=SERVER, 3=CLIENT, 4=PRODUCER, 5=CONSUMER */
  span_kind: number;
  /** OTel StatusCode enum: 0=UNSET, 1=OK, 2=ERROR */
  status_code: number;
  status_message: string;
  service_name: string;
  gen_ai_system: string;
  request_model: string;
  response_model: string;
  input_tokens: number;
  output_tokens: number;
  finish_reasons: string;
  input_messages: string;
  output_messages: string;
  /**
   * All span attributes verbatim, keyed by their OTel attribute name.
   * Includes OTel GenAI semconv (gen_ai.*), OpenInference (llm.*,
   * openinference.*), and anything else the instrumentation emits.
   */
  attributes: Record<string, string>;
}

export interface TraceDetail {
  trace_id: string;
  spans: Span[];
}

/** Outcome label produced by the deterministic decision summary analyzer
 *  (see `backend/app/summary.py`). */
export type DecisionOutcome = "answered" | "refused" | "partial" | "errored" | "unknown";

export interface ToolUsage {
  name: string;
  calls: number;
  errors: number;
}

export interface RetrievalUsage {
  name: string;
  calls: number;
}

export interface GuardrailUsage {
  name: string;
  triggered: boolean;
}

export interface DecisionMetrics {
  duration_ms: number;
  total_tokens: number;
  span_count: number;
  error_count: number;
}

/** One node in the decision path — a single non-plumbing operation in
 *  execution order. Consecutive duplicates collapse into one step with
 *  `count > 1` (a retry / iteration). */
export interface DecisionStep {
  /** llm | tool | retriever | reranker | guardrail | agent | other */
  kind: string;
  name: string;
  count: number;
  detail?: string | null;
}

/** Stable flag IDs — must match the FLAG_* constants in
 *  `backend/app/summary.py`. The frontend matches on `id` to pick an icon. */
export type DecisionFlagId =
  | "truncated_output"
  | "tool_failure"
  | "retry_loop"
  | "near_context_limit"
  | "instrumentation_gap";

export interface DecisionFlag {
  id: DecisionFlagId | string; // string for forward-compat with new backend flags
  severity: "info" | "warning";
  label: string;
  detail: string;
}

/**
 * Audit-focused summary of a single trace, generated by the backend's
 * deterministic analyzer. Trace-wide (not span-scoped), independent from the
 * raw span list, fetched from `GET /api/v1/traces/{id}/summary`.
 */
export interface DecisionRecord {
  /** User question extracted from the root (or first LLM) span. `null` when
   *  the instrumented app did not capture message content. */
  goal: string | null;
  goal_truncated: boolean;
  outcome: DecisionOutcome;
  /** One-sentence justification of the outcome. */
  outcome_reason: string;
  /** True when the outcome was inferred via a Hybrid fallback rule (e.g.
   *  guardrail span errored without an explicit `guardrail.triggered=true`).
   *  Frontend renders a `(heuristic)` badge in that case. */
  outcome_reason_heuristic: boolean;
  final_answer: string | null;
  final_answer_truncated: boolean;
  /** Ordered list of decision-relevant operations (LLM/Tool/Retriever/...).
   *  Plumbing spans are filtered out, consecutive duplicates collapse. */
  decision_path: DecisionStep[];
  /** Anomaly flags surfaced by the analyzer — empty when the trace looks clean. */
  flags: DecisionFlag[];
  models_used: string[];
  tools_used: ToolUsage[];
  retrievals: RetrievalUsage[];
  guardrails: GuardrailUsage[];
  metrics: DecisionMetrics;
}

export interface TracesResponse {
  items: Trace[];
  total: number;
  limit: number;
  offset: number;
}

// Read the backend base URL from a build-time env var (per repo convention —
// alerts / ai-system-registry do the same). Defaults to the relative "/api/v1"
// so the deliberate proxy setup keeps working out of the box: Vite proxies it
// in dev, nginx proxies it in prod. Override VITE_DTA_API_BASE only when the
// platform is deployed behind a path prefix or a proxy that doesn't preserve
// /api/. Relative default also stays iframe-safe (see fetchTraces below).
const BASE = import.meta.env.VITE_DTA_API_BASE ?? "/api/v1";

/** Fetch JSON, with a clearer error than Safari's "The string did not match the
 *  expected pattern" when the response is HTML (e.g. Vite's SPA fallback because
 *  the dev proxy isn't routing /api). */
async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} on ${url}`);
  const ct = res.headers.get("content-type") ?? "";
  if (!ct.includes("application/json")) {
    throw new Error(
      `Expected JSON from ${url} but got "${ct}". ` +
        `Is the backend running on :8006 and is the Vite proxy configured?`
    );
  }
  return res.json() as Promise<T>;
}

export async function fetchTraces(params: {
  limit?: number;
  offset?: number;
} & TraceFilters): Promise<TracesResponse> {
  // Build query string manually — avoids `new URL(...)` which throws
  // "The string did not match the expected pattern" in sandboxed iframes
  // (e.g. inside the Luigi shell) where window.location.origin can be "null".
  const qs = new URLSearchParams();
  if (params.limit != null) qs.set("limit", String(params.limit));
  if (params.offset != null) qs.set("offset", String(params.offset));
  if (params.trace_id) qs.set("trace_id", params.trace_id);
  if (params.service_name) qs.set("service_name", params.service_name);
  if (params.model) qs.set("model", params.model);
  if (params.from) qs.set("from", params.from);
  if (params.to) qs.set("to", params.to);
  if (params.errors_only) qs.set("errors_only", "true");

  const res = await fetchJson<TracesResponse>(`${BASE}/traces?${qs.toString()}`);
  return res;
}

/**
 * Normalize attribute keys to lowercase so consumers don't need to handle
 * casing variants emitted by different frameworks (e.g. "Gen_Ai.System" vs
 * "gen_ai.system", or uppercase keys from Haystack / Semantic Kernel).
 * Values are left untouched — only keys are folded.
 */
function normalizeAttributes(attrs: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(attrs)) {
    const lower = k.toLowerCase();
    // Last writer wins when two keys differ only in case (extremely rare).
    out[lower] = v;
  }
  return out;
}

export async function fetchTraceDetail(traceId: string): Promise<TraceDetail> {
  const detail = await fetchJson<TraceDetail>(`${BASE}/traces/${encodeURIComponent(traceId)}`);
  return {
    ...detail,
    spans: detail.spans.map((s) => ({
      ...s,
      attributes: s.attributes ? normalizeAttributes(s.attributes) : {},
    })),
  };
}

/**
 * Fetch the deterministic decision summary for a single trace. Loaded in
 * parallel with `fetchTraceDetail` from `TraceDetail.tsx` so summary
 * rendering doesn't block span rendering (and vice versa).
 *
 * Returns 404 when the trace has no spans — the caller treats that the same
 * as an error and shows the fallback in the summary card.
 */
export async function fetchTraceSummary(traceId: string): Promise<DecisionRecord> {
  return fetchJson<DecisionRecord>(
    `${BASE}/traces/${encodeURIComponent(traceId)}/summary`
  );
}
